// Code generated by "stringer -type=Artist -linecomment"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ArtistLedZeppelin-1]
	_ = x[ArtistPinkFloyd-2]
	_ = x[ArtistPostMalone-3]
	_ = x[ArtistShaboozey-4]
}

const _Artist_name = "led zepplinpink floydpost maloneShaboozey"

var _Artist_index = [...]uint8{0, 11, 21, 32, 41}

func (i Artist) String() string {
	i -= 1
	if i < 0 || i >= Artist(len(_Artist_index)-1) {
		return "Artist(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Artist_name[_Artist_index[i]:_Artist_index[i+1]]
}
