// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.1
// source: myServerCall.proto

package myServerCall

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name and numbers
type MyCall struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Num1 int32  `protobuf:"varint,2,opt,name=Num1,proto3" json:"Num1,omitempty"`
	Num2 int32  `protobuf:"varint,3,opt,name=Num2,proto3" json:"Num2,omitempty"`
}

func (x *MyCall) Reset() {
	*x = MyCall{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myServerCall_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyCall) ProtoMessage() {}

func (x *MyCall) ProtoReflect() protoreflect.Message {
	mi := &file_myServerCall_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyCall.ProtoReflect.Descriptor instead.
func (*MyCall) Descriptor() ([]byte, []int) {
	return file_myServerCall_proto_rawDescGZIP(), []int{0}
}

func (x *MyCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MyCall) GetNum1() int32 {
	if x != nil {
		return x.Num1
	}
	return 0
}

func (x *MyCall) GetNum2() int32 {
	if x != nil {
		return x.Num2
	}
	return 0
}

// The response message containing the status
type MyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32 `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *MyReply) Reset() {
	*x = MyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myServerCall_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyReply) ProtoMessage() {}

func (x *MyReply) ProtoReflect() protoreflect.Message {
	mi := &file_myServerCall_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyReply.ProtoReflect.Descriptor instead.
func (*MyReply) Descriptor() ([]byte, []int) {
	return file_myServerCall_proto_rawDescGZIP(), []int{1}
}

func (x *MyReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_myServerCall_proto protoreflect.FileDescriptor

var file_myServerCall_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x79, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x61, 0x6c, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6d, 0x79, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x61,
	0x6c, 0x6c, 0x22, 0x44, 0x0a, 0x06, 0x4d, 0x79, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x75, 0x6d, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x4e, 0x75, 0x6d, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x75, 0x6d, 0x32, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x4e, 0x75, 0x6d, 0x32, 0x22, 0x21, 0x0a, 0x07, 0x4d, 0x79, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x49, 0x0a, 0x0c, 0x4d,
	0x79, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x39, 0x0a, 0x08, 0x53,
	0x65, 0x72, 0x76, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x14, 0x2e, 0x6d, 0x79, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x43, 0x61, 0x6c, 0x6c, 0x2e, 0x4d, 0x79, 0x43, 0x61, 0x6c, 0x6c, 0x1a, 0x15, 0x2e,
	0x6d, 0x79, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x61, 0x6c, 0x6c, 0x2e, 0x4d, 0x79, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x0f, 0x5a, 0x0d, 0x2f, 0x6d, 0x79, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_myServerCall_proto_rawDescOnce sync.Once
	file_myServerCall_proto_rawDescData = file_myServerCall_proto_rawDesc
)

func file_myServerCall_proto_rawDescGZIP() []byte {
	file_myServerCall_proto_rawDescOnce.Do(func() {
		file_myServerCall_proto_rawDescData = protoimpl.X.CompressGZIP(file_myServerCall_proto_rawDescData)
	})
	return file_myServerCall_proto_rawDescData
}

var file_myServerCall_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_myServerCall_proto_goTypes = []any{
	(*MyCall)(nil),  // 0: myServerCall.MyCall
	(*MyReply)(nil), // 1: myServerCall.MyReply
}
var file_myServerCall_proto_depIdxs = []int32{
	0, // 0: myServerCall.MyServerCall.ServCall:input_type -> myServerCall.MyCall
	1, // 1: myServerCall.MyServerCall.ServCall:output_type -> myServerCall.MyReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_myServerCall_proto_init() }
func file_myServerCall_proto_init() {
	if File_myServerCall_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_myServerCall_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*MyCall); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_myServerCall_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*MyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_myServerCall_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_myServerCall_proto_goTypes,
		DependencyIndexes: file_myServerCall_proto_depIdxs,
		MessageInfos:      file_myServerCall_proto_msgTypes,
	}.Build()
	File_myServerCall_proto = out.File
	file_myServerCall_proto_rawDesc = nil
	file_myServerCall_proto_goTypes = nil
	file_myServerCall_proto_depIdxs = nil
}
